<?php
/** @var \Kiruthika\Helloworld\Block $block */
$data = $block->getEditData();
?>

<div class="template">
    <h1>Edit Data</h1>
    <form action="<?= $block->getAddUrl(); ?>" method="post">
    <input type="hidden" value="<?= $data['id']; ?>" name="id">
    <div class="form-group">
        <label>Name</label>
        <input type="text" name="name" class="form-control" value="<?= $data['name']; ?>">
    </div>  
    <div class="form-group">
        <label>Description</label>
        <input type="text" name="description" class="form-control" value="<?= $data['description']; ?>">
    </div> 
    <div class="form-group">
        <input type="submit" name="submit" class="btn btn-success" value="EDIT">
    </div> 
</form>
</div>